-- CreateTable
CREATE TABLE "GaudiResponse" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completionPercentage" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "originStory" TEXT,
    "ahaMoment" TEXT,
    "frustrationDescription" TEXT,
    "gaudiStartDate" TIMESTAMP(3),
    "automation6MonthsAgo" INTEGER,
    "currentAutomation" INTEGER,
    "targetAutomation12Months" INTEGER,
    "valuePropAudience" TEXT,
    "valuePropOutcome" TEXT,
    "valuePropMethod" TEXT,
    "valuePropFraming" TEXT,
    "capabilities" TEXT[],
    "aiHandles" TEXT,
    "humansHandle" TEXT,
    "outputTypes" TEXT[],
    "impactEngineers" TEXT,
    "impactCompany" TEXT,
    "impactClients" TEXT,
    "caseStudyExample" TEXT,
    "metricsData" JSONB,
    "vibeAttributes" TEXT[],
    "toneCasualToProfessional" INTEGER,
    "tonePlayfulToSerious" INTEGER,
    "toneBoldToUnderstated" INTEGER,
    "toneStartupToEnterprise" INTEGER,
    "companiesAdmired" TEXT,
    "analogyCar" TEXT,
    "analogyPerson" TEXT,
    "analogyBuilding" TEXT,
    "storytellingDepth" TEXT,
    "sectionPriority" TEXT[],
    "heroFocus" TEXT,
    "pageHierarchy" TEXT[],
    "homepageSections" JSONB,
    "homepagePriority" TEXT[],
    "journeyJobCandidate" JSONB,
    "journeyAckSite" JSONB,
    "journeyCompetitor" JSONB,
    "navItems" TEXT[],
    "ctaHeader" TEXT,
    "ctaHero" TEXT,
    "ctaFooter" TEXT,
    "contentDepth" JSONB,
    "conversionGoals" TEXT[],
    "ctaCareersButton" TEXT,
    "ctaCareersSupporting" TEXT,
    "ctaContactButton" TEXT,
    "ctaContactSupporting" TEXT,
    "objections" JSONB,
    "trustSignals" TEXT[],
    "trustSignalsLocation" TEXT,
    "aiTransparencyLevel" TEXT,
    "proprietaryVsOpen" TEXT,
    "humanAiFraming" TEXT,
    "availableAssets" TEXT[],
    "projectsAutomated" INTEGER,
    "hoursSavedPerProject" DOUBLE PRECISION,
    "accuracyImprovement" INTEGER,
    "currentAutomationPercent" INTEGER,
    "targetAutomationPercent" INTEGER,
    "teamSize" INTEGER,
    "candidateExperienceLevel" TEXT,
    "candidateTechnicalSkills" TEXT,
    "candidateNiceToHave" TEXT,
    "candidateCultureFit" TEXT,
    "candidateMotivations" TEXT[],
    "candidateQuestions" TEXT[],
    "careerUniqueSelling" TEXT[],
    "careerProblemsToSolve" TEXT,
    "careerGrowth" TEXT,
    "officeLocation" TEXT,
    "remotePolicy" TEXT,
    "careerTeamSize" INTEGER,
    "careerVibe" TEXT,
    "careerPerks" TEXT,
    "openRoles" JSONB,
    "noOpeningsHandling" TEXT[],
    "heroAnimationStyle" TEXT,
    "primaryAccentColor" TEXT,
    "colorTemperature" TEXT,
    "visualEnergy" INTEGER,
    "imageryStyles" TEXT[],
    "ackRelationshipClarity" TEXT,
    "ackCredibilityVsDistraction" TEXT,
    "successVisitorActions" TEXT[],
    "primaryConversionGoals" TEXT[],
    "benchmarkCareerVisit" INTEGER,
    "benchmarkApplicationRate" INTEGER,
    "benchmarkTimeOnSite" INTEGER,
    "benchmarkPagesPerSession" DOUBLE PRECISION,
    "benchmarkBounceRate" INTEGER,
    "perfScrollDepth" INTEGER,
    "perfHowItWorks" INTEGER,
    "perfAnimationCompletion" INTEGER,
    "perfCtaClickRate" INTEGER,
    "message1Complete" TEXT,
    "message2Complete" TEXT,
    "message3Complete" TEXT,
    "wordsRight" TEXT[],
    "wordsAvoid" TEXT[],
    "voiceToneAttributes" TEXT[],
    "sentenceStructure" TEXT,
    "jargonLevel" TEXT,
    "gaudiOneWord" TEXT,
    "visitorFeeling" TEXT,
    "firstThought" TEXT,
    "misconception" TEXT,
    "mostExciting" TEXT,
    "superpower" TEXT,
    "fiveYearVision" TEXT,
    "techcrunchHeadline" TEXT,
    "otherNotes" TEXT,
    "existingContentAssets" TEXT[],
    "contentStorageLocation" TEXT,
    "contentToCreate" TEXT[],
    "competitorsReferences" TEXT,
    "adminNotes" TEXT,
    "isReviewed" BOOLEAN NOT NULL DEFAULT false,
    "reviewStatus" TEXT NOT NULL DEFAULT 'pending',
    "reviewedAt" TIMESTAMP(3),
    "lastPageVisited" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "GaudiResponse_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "GaudiResponse_status_idx" ON "GaudiResponse"("status");

-- CreateIndex
CREATE INDEX "GaudiResponse_createdAt_idx" ON "GaudiResponse"("createdAt");

-- CreateIndex
CREATE INDEX "GaudiResponse_isReviewed_idx" ON "GaudiResponse"("isReviewed");
